version: '3.8'

services:
  maven:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shareddata
        target: /tmp/shareddata
  tomcat:
    depends_on:
      - maven
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: shareddata
        target: /tmp/shareddata
volumes:
  shareddata: 