FROM alpine:3.14
RUN apt update &&b install -y default-jdk wget
RUN mkdir /usr/local/tomcat
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz -O /tmp/tomcat.tar.gz
RUN cd /tmp && tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-9.0.69/* /usr/local/tomcat/
RUN cp /tmp/shareddata/* /usr/local/tomcat/webapps
RUN rm -rf /tmp/shareddata/*
EXPOSE 8080
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]