version: '3.8'

services:
  maven:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - shareddata:./tmp/shareddata
  tomcat:
    depends_on:
      - maven
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - '8080:8080'
    volumes:
      - shareddata:./tmp/shareddata
volumes:
  shareddata: 