version: '3.9'

services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "sharedartefact:/target/"
  tomcat:
    depends_on:
      - maven
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - '8080:8080'
    volumes:
      - "webapps:/usr/local/tomcat/webapps"
volumes:
  sharedartefact:
  webapps: